#!/bin/bash

#should I do this on startvnc?
vglclient &

XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &
export PATH=$PATH:/mrtrix3/bin

#vglrun mrview `find $INPUT_DIR -name *.nii.gz` &
if [ -f $INPUT_DIR/t1.nii.gz ]; then
    vglrun mrview -load $INPUT_DIR/t1.nii.gz -fullscreen &
fi

if [ -f $INPUT_DIR/t2.nii.gz ]; then
    vglrun mrview -load $INPUT_DIR/t2.nii.gz -fullscreen &
fi

if [ -f $INPUT_DIR/dwi.nii.gz ]; then
    vglrun mrview -load $INPUT_DIR/dwi.nii.gz -fullscreen &
fi

if [ -f $INPUT_DIR/bold.nii.gz ]; then
    vglrun mrview -load $INPUT_DIR/bold.nii.gz -fullscreen &
fi

if [ -f $INPUT_DIR/track.tck ]; then
    tckmap -vox 1,1,1 $INPUT_DIR/track.tck /tmp/mask.nii.gz
    vglrun mrview -load /tmp/mask.nii.gz -tractography.load $INPUT_DIR/track.tck -fullscreen &
fi

#TODO - we should use a single mrview and open 3 tracks..
for type in DT_STREAM SD_STREAM SD_PROB
do
    if [ -f $INPUT_DIR/output.$type.tck ]; then
        tckmap -vox 1,1,1 $INPUT_DIR/output.$type.tck /tmp/mask.nii.gz
        vglrun mrview -load /tmp/mask.nii.gz -tractography.load $INPUT_DIR/output.$type.tck -fullscreen &
    fi
done

#wait for mrview to start
#sleep 2

#find the window id (-fullscreen option should take care of this)
#id=`wmctrl -pl | grep " $pid " | cut -f 1 -d " "`
#echo $id > /id.txt
#wmctrl -i -r $id -b add,fullscreen

sleep 3600
